branch-defaults:
  master:
    environment: Bookmaker-production
environment-defaults:
  Bookmaker-production:
    branch: null
    repository: null
global:
  application_name: Bookmaker
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:us-east-1::platform/Puma with Ruby 2.5 running on 64bit Amazon Linux/2.8.6
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application